### ISSUE TITLE
problem with build_graph.py

### ISSUE THREAD

**Issue by LoeliaBabin** [WangHYLab/fcirc#3]
I encounter problem when runnin build_graph.py
I have this message : Failed to build the bipartite graph pairs
I used Homo_sapiens.GRCh38.dna.primary_assembly.fa for genome and Homo_sapiens.GRCh38.90.gtf for gtf
(I changed the - by -- in the first column of fusion_table.tsv)
Could you help me to solve this problem ?

**Comment by zhixue** [comment]
Hi.  
We have fixed this problem, please re-download codes again. "--" is used to connect fusion gene pairs instead of "-". 

Thank you for your report.
